# Generated by Django 4.0.6 on 2022-11-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cou_title', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='dreamit/image')),
                ('time', models.TimeField()),
            ],
        ),
    ]
