# Generated by Django 4.0.6 on 2022-11-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamit', '0004_subcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='ch_name',
            new_name='sub_name',
        ),
    ]
